services:
  app-python:
    build:
      context: ../app_python
    container_name: fastapi-app
    ports:
      - "8000:8000"
    networks:
      - monitoring
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
        max-file: "3"
    mem_limit: 500m
    cpus: "0.5"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    volumes:
      - ./logs:/var/log/app_logs

  app-go:
    build:
      context: ../app_go
    container_name: gin-app
    ports:
      - "8080:8080"
    networks:
      - monitoring
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
        max-file: "3"
    mem_limit: 500m
    cpus: "0.5"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    volumes:
      - ./logs:/var/log/app_logs


  loki:
    image: grafana/loki:latest
    container_name: loki
    user: "1000:1000"
    volumes:
      - ./loki-cfg.yml:/etc/loki/local-config.yaml
      - ./loki-data:/loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - monitoring
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
        max-file: "3"
    mem_limit: 1g
    cpus: "0.5"

  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy
      - ./logs:/var/log/app_logs:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    networks:
      - monitoring
    restart: always
    depends_on:
      - loki
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
        max-file: "3"
    mem_limit: 500m
    cpus: "0.3"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=root1234
    networks:
      - monitoring
    restart: always
    depends_on:
      - loki
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
        max-file: "3"
    mem_limit: 1g
    cpus: "0.5"
  
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    networks:
      - monitoring
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
        max-file: "3"
    mem_limit: 500m
    cpus: "0.3"

networks:
  monitoring:

volumes:
  grafana_data:
