- name: Install required packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present
    update_cache: yes

- include_tasks: install_docker.yml

- name: Ensure Docker is running
  systemd:
    name: docker
    enabled: yes
    state: started

- include_tasks: install_compose.yml