- name: Install packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present
    update_cache: yes

- include_tasks: install_docker.yml

- include_tasks: install_compose.yml

- name: Enable Docker service to start on boot
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Add current user to docker group
  user:
    name: "{{ ansible_user }}"
    groups:
      - docker
    append: yes
